package com.apirest.backend.models.enums.Curriculum;

public enum AreaConocimientoCurriculum {
    AGRONOMIA_VETERINARIA_Y_AFINES,
    BELLAS_ARTES,
    CIENCIAS_DE_LA_EDUCACION,
    CIENCIAS_DE_LA_SALUD,
    CIENCIAS_SOCIALES_Y_HUMANAS,
    CIENCIAS_SOCIALES_DERECHO_CIENCIAS_POLITICAS,
    CIENCIAS_Y_HUMANIDADES_PERSONALES,
    ECONOMIA_ADMINISTRACION_CONTADURIA_Y_AFINES,
    GENERICA,
    HUMANIDADES_Y_CIENCIAS_RELIGIOSAS,
    INGENIERIA_ARQUITECTURA_URBANISMO_Y_AFINES,
    MATEMATICAS_Y_CIENCIAS_NATURALES,
    NO_APLICA
}
