package com.apirest.backend.models.enums.Curriculum;

public enum DescripcionDocumentoAdicionalCurriculum {
    TABLA_PARAMÉTRICA_TIPO_DOCUMENTOS_ADICIONALES,
    TIPO_DOCUMENTOS_ADICIONALES_CERTIFICADO_DE_DISCAPACIDAD,
    TIPO_DE_DOCUMENTO_Registro_Único_Nacional_del_Talento_Humano_en_Salud,
    TABLA_PARAMETRICA_TIPO_DOCUMENTOS_ADICIONALES,
    REGISTRO_DE_DEUDORES_ALIMENTARIOS_MOROSOS_REDAM,
    Tipo_de_documento,
    TIPO_DOCUMENTOS_ADICIONALES_REGISTRO_CIVIL,
    TIPO_DOCUMENTOS_ADICIONALES_LICENCIA_DE_CONDUCCIÓN,
    TIPO_DOCUMENTOS_ADICIONALES_PASADO_JUDICIAL,
    TIPO_DOCUMENTOS_ADICIONALES_CERT_ANTECEDENTES_DISCIPLINARIOS,
    TIPO_DOCUMENTOS_ADICIONALES_CERT_ANTECEDENTES_FISCALES,
    TIPO_DOCUMENTOS_ADICIONALES_LICENCIA_CONDUCCIÓN_MOTOCICLETA,
    TIPO_DOCUMENTOS_ADICIONALES,
    TIPO_DOCUMENTOS_ADICIONALES_EDUCACIÓN_COMPLEMENTARIA
}
