package com.apirest.backend.models.enums.Curriculum;

public enum TipoDocumentoCurriculum {
    CERTIFICADO_DE_DELITOSSEXUALES,
    CERTIFICADO_DE_DISCAPACIDAD,
    CERTIFICADO_RETHUS,
    OTRO,
    REGISTRO_DE_DEUDORES_ALIMENTARIOS_MOROSOS_REDAM,
    Registro_Unico_Tributario_RUT,
    REGISTRO_CIVIL,
    LICENCIA_DE_CONDUCCIÓN,
    PASADO_JUDICIAL,
    CERT_ANTECEDENTES_DISCIPLINARIOS,
    CERT_ANTECEDENTES_FISCALES,
    LICENCIA_CONDUCCIÓN_MOTOCICLETA,
    CERT_ANTECEDENTES_ABOGADO,
    EDUCACIÓN_COMPLEMENTARIA
}
