spring.application.name=backend

#BD
spring.data.mongodb.uri=${SPRING_MONGODB_URI:mongodb+srv://juanvila_db_user:95JNtH2Ujz7UKlYn@cluster0.qfukbh5.mongodb.net/BD-SIGED-II}
spring.data.mongodb.database=${SPRING_MONGODB_DATABASE:BD-SIGED-II}

#Token
jwt.llave = tp81f40tGgJwpGzePE2A33g/WJhmb+hprud2Oxzi+yY=
jwt.expiracion = 3600000

#Resend api email
resend.api.key = re_WFgmw5T6_15eujXh21LKDb1qFgat2ordS

# Archivos cargados por usuarios
app.upload-dir=${APP_UPLOAD_DIR:uploads}
app.upload.max-size-bytes=${APP_UPLOAD_MAX_SIZE_BYTES:10485760}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
